export const ActionTypes = {
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_ALL_PRODUCTS: "GET_ALL_PRODUCTS",
  GET_PRODUCTS_SEARCH: "GET_PRODUCTS_SEARCH",
  PRODUCT_DETAIL: "PRODUCT_DETAIL",
  CLEAN_PRODUCT_DETAIL: "CLEAN_PRODUCT_DETAIL",
  PRODUCT_CREATED: "PRODUCT_CREATED",
  GET_PRODUCTS_QUERY: "GET_PRODUCTS_QUERY",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",
  EMPTY_PRODUCT_CREATED: "EMPTY_PRODUCT_CREATED",
  CLEAN_CATALOGUE: "CLEAN_CATALOGUE",

  GET_ORDERS: "GET_ORDERS",
  ORDER_DETAIL: "ORDER_DETAIL",

  GET_CATEGORIES: "GET_CATEGORIES",

  GET_BRANDS: "GET_BRANDS",
  UPDATE_BRAND: "UPDATE_BRAND",

  ADD_DB_PRODUCT_CART: "ADD_DB_PRODUCT_CART",
  ADD_PRODUCT_CART: "ADD_PRODUCT_CART",
  REMOVE_PRODUCT_CART: "REMOVE_PRODUCT_CART",
  REMOVE_CART_PRODUCT_LS: "REMOVE_CART_PRODUCT_LS",

  CREATE_USER: "CREATE_USER",
  LOGIN_USER: "LOGIN_USER",
  CLEAN_SIGNUP: "CLEAN_SIGNUP",

  ADD_FAV_PRODUCT: "ADD_FAV_PRODUCT",
  REMOVE_FAV_PRODUCT: "REMOVE_FAV_PRODUCT",

  CONFIRM_CHECKOUT: "CONFIRM_CHECKOUT",
};

export const URLS = {
  URL_CHECKOUT: "http://localhost:3001/checkout",
  URL_PRODUCTS: "http://localhost:3001/products",
  URL_ALL_PRODUCTS: "http://localhost:3001/allproducts",
  URL_USER_ORDERS: "http://localhost:3001/orders",
  URL_CATEGORIES: "http://localhost:3001/categories",
  URL_BRANDS: "http://localhost:3001/brands",
  URL_SIGNUP: "http://localhost:3001/signup",
  URL_LOGIN: "http://localhost:3001/login",
  URL_USERS: "http://localhost:3001/users",
};
