export const ActionTypes = {
	GET_PRODUCTS: 'GET_PRODUCTS',
	PRODUCT_DETAIL: 'PRODUCT_DETAIL',
	PRODUCT_CREATED: 'PRODUCT_CREATED',
	GET_PRODUCTS_QUERY: 'GET_PRODUCTS_QUERY',
	UPDATE_PRODUCT: 'UPDATE_PRODUCT',
	EMPTY_PRODUCT_CREATED: 'EMPTY_PRODUCT_CREATED',

	GET_ORDERS: 'GET_ORDERS',
	ORDER_DETAIL: 'ORDER_DETAIL',

	GET_CATEGORIES: 'GET_CATEGORIES',
};

export const URLS = {
	URL_PRODUCTS: 'http://localhost:3001/products',
	URL_ORDERS: 'http://localhost:3001/orders',
	URL_CATEGORIES: 'http://localhost:3001/categories',
};
